project_id = "anhedsbftzisrmawvoxv"

[functions.ai-assistant]
enabled = true
verify_jwt = false

[functions.telegram-post]
enabled = true
verify_jwt = false

[functions.fetch-deals]
enabled = true
verify_jwt = false

[functions.process-schedule]
enabled = true
verify_jwt = false

[functions.upstox-market-data]
enabled = true
verify_jwt = false